create table
  public.attendance_record (
    student_number integer not null,
    class_id integer not null,
    attendance integer not null default 0,
    constraint attendance_record_pkey primary key (student_number, class_id),
    constraint public_attendance_record_class_id_fkey foreign key (class_id) references class (class_id) on update cascade on delete cascade,
    constraint public_attendance_record_student_number_fkey foreign key (student_number) references student_details (student_number) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.class (
    class_id integer generated by default as identity,
    name character varying not null,
    curr_sessions integer not null default 0,
    max_absences integer not null default 0,
    start_time time without time zone null default now(),
    end_time time without time zone null default now(),
    enrollment_key integer not null,
    constraint class_pkey primary key (class_id),
    constraint class_class_id_key unique (class_id),
    constraint class_enrollment_key_key unique (enrollment_key)
  ) tablespace pg_default;

create table
  public.handlers (
    professor_id integer not null,
    handler_id integer generated by default as identity,
    class_id integer null,
    constraint handlers_pkey primary key (handler_id),
    constraint handlers_handlers_id_key unique (handler_id),
    constraint public_handlers_class_id_fkey foreign key (class_id) references class (class_id) on update cascade on delete cascade,
    constraint public_handlers_professor_id_fkey foreign key (professor_id) references professor_details (professor_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.learners (
    learner_id integer generated by default as identity,
    student_id integer not null,
    class_id integer null,
    constraint learners_pkey primary key (learner_id),
    constraint learners_learner_id_key unique (learner_id),
    constraint public_learners_class_id_fkey foreign key (class_id) references class (class_id) on update cascade on delete cascade,
    constraint public_learners_student_id_fkey foreign key (student_id) references student_details (student_number) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.professor_creds (
    email character varying not null,
    password character varying not null,
    constraint professor_creds_pkey primary key (email)
  ) tablespace pg_default;

create table
  public.professor_details (
    professor_id integer generated by default as identity,
    first_name character varying not null,
    last_name character varying not null,
    email character varying not null,
    constraint professor_pkey primary key (professor_id),
    constraint professor_professor_id_key unique (professor_id),
    constraint public_professor_details_email_fkey foreign key (email) references professor_creds (email) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.student_creds (
    email character varying not null,
    password character varying not null,
    constraint student_creds_pkey primary key (email)
  ) tablespace pg_default;

create table
  public.student_details (
    student_number integer not null,
    first_name character varying not null,
    last_name character varying not null,
    email character varying not null,
    constraint student_pkey primary key (student_number),
    constraint student_student_number_key unique (student_number)
  ) tablespace pg_default;